### ISSUE TITLE
pod install fail cause:[!] Invalid `Podfile` file: [!] Unsupported options `{:exclusive=>true}` for target `NVMImageMaker_Example`..

### ISSUE THREAD

**Issue by momo462** [eleme/NVMImageMaker#3]

**Comment by momo462** [comment]
https://stackoverflow.com/questions/42344038/how-to-solve-this-error-like-invalid-podfile-file-unsupported-options

you should rewrite your podfile

**Comment by axl411** [comment]
Thanks for pointing that out. Updated and fixed.
